export const ACTIONS = Object.freeze({
    GET_STATE: 'getState',
    START: 'start',
    PAUSE: 'pause',
    RESET: 'reset',
    RESET_TIMER: 'resetTimer',
    SKIP_BREAK: 'skipBreak',
    TOGGLE_TIMER: 'toggleTimer',
    SAVE_SETTINGS: 'saveSettings',
    CREATE_TASK: 'createTask',
    UPDATE_TASK: 'updateTask',
    DELETE_TASK: 'deleteTask',
    COMPLETE_TASKS: 'completeTasks',
    DELETE_TASKS: 'deleteTasks',
    GET_TASKS: 'getTasks',
    RECONFIGURE_JIRA_SYNC: 'reconfigureJiraSync',
    IMPORT_JIRA_TASKS: 'importJiraTasks',
    SET_CURRENT_TASK: 'setCurrentTask',
    UPDATE_UI_PREFERENCES: 'updateUiPreferences',
    CLEAR_COMPLETED_TASKS: 'clearCompletedTasks',
    CLEAR_STATISTICS: 'clearStatistics',
    GET_STATISTICS_HISTORY: 'getStatisticsHistory',
    CHECK_NOTIFICATIONS: 'checkNotifications',
    UPDATE_TIMER: 'updateTimer',
    PLAY_SOUND: 'playSound',
});
